# Generated by Django 4.2.3 on 2023-07-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='phone_number',
        ),
    ]
